config/routes.rb
Gmh::Application.routes.draw do |map|
  resources :campaigns do
    resources :characters
    resources :encounters do
      member do
        get :init, :run
        post :init, :increment_round, :decrement_round
      end
    end
  end

  resources :encounters do
    member do
      get :init
      post :run
    end
  end

  root :to => "campaigns#index"

end

app/models/encounter.rb
class Encounter
  include Mongoid::Document

  field :name, :type => String
  field :character_ids, :type => Array, :default => []
  field :monsters, :type => Array, :default => []
  field :round, :type => Integer, :default => 1

  belongs_to_related :campaign

  def initialize_characters(data)
    return if data.nil? || data.empty?

    data.each do |char_id, roll|
      character = characters.detect {|c| c.id == char_id}
      init = roll[:roll].to_i + character.base_initiative
      character.update_attributes(:current_initiative => init)
    end
  end

  def update_characters(updated_characters)
    return if characters.nil? || characters.empty?

    updated_characters.each do |char_id, attributes|
      character = characters.detect {|c| c.id == char_id}
      character.update_attributes(attributes)
    end
  end

  def characters
    campaign.characters.find(:all).select {|x| character_ids.include?(x.id)}
  end
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController

  before_filter :find_campaign
  before_filter :find_encounter, :only => [:init, :run, :show, :edit, :update, :destroy, :increment_round, :decrement_round]

  def find_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def find_encounter
    @encounter = @campaign.encounters.find(params[:id])
  end

  def index
    @encounters = @campaign.encounters.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def init
    if params.has_key?(:characters)
      @encounter.initialize_characters(params[:characters])
      redirect_to :action => :run
    else
      @campaign_characters = @campaign.characters.all
      @characters = @encounter.characters
    end
  end

  def run
    @characters = @encounter.characters.sort_by(&:current_initiative).reverse
  end

  def show
    @characters = @encounter.characters

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    encounter_attributes = params.fetch(:encounter, {})
    @encounter = @campaign.encounters.build(encounter_attributes)

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @characters = @encounter.characters
    @campaign_characters = @campaign.characters.all
  end

  def create
    @encounter = @campaign.encounters.build(params[:encounter])

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to([@campaign, @encounter], :notice => 'Encounter was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      character_ids = (params[:encounter][:character_ids] + @encounter.character_ids).uniq

      if @encounter.update_attributes(params[:encounter])
        @encounter.character_ids = character_ids
        @encounter.save

        format.html { redirect_to([@campaign, @encounter], :notice => 'Encounter was successfully updated.') }
        format.js { render :js => true.to_json }
      else
        format.html { render :action => "edit" }
        format.js { render :js => false.to_json }
      end
    end
  end

  def increment_round
    @encounter.update_attributes(:round => @encounter.round + 1)
    @encounter.update_characters(params[:characters])
    respond_to do |format|
      format.js { render :js => url_for(:action => :run, :controller => :encounters).to_json}
    end
  end

  def decrement_round
    @encounter.update_attributes(:round => @encounter.round - 1)
    @encounter.update_characters(params[:characters])
    respond_to do |format|
      format.js { render :js => url_for(:action => :run, :controller => :encounters, :anchor => "foo").to_json}
    end
  end

  def destroy
    @encounter.destroy

    respond_to do |format|
      format.html { redirect_to(campaign_encounters_path(@campaign)) }
    end
  end
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/views/encounters/_form.html.haml
= form_for [@campaign, @encounter] do |f|
  -if @encounter.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@encounter.errors.count, "error")} prohibited this encounter from being saved:"
      %ul
        - @encounter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/encounters/edit.html.haml
%h1 Editing encounter

= render 'form'

%p
  %h2 Charcters in campaign
  = render :partial => "characters/list", :locals => {:characters => @campaign_characters}
%p
  %h2 Charcters in encounter
  = form_for [@campaign, @encounter], :url => init_campaign_encounter_path(@campaign, @encounter), :html => {:method => 'post', :class => "characters_list"} do |f|
    %table#initialization
      %tr
        %th Name
        %th Base Initiative
        %th Initiative Roll

      - @characters.each do |character|
        %tr.character
          %td.name= character.name
          %td.base_initiative= character.base_initiative
          %td
            %input{:id => "characters_#{character.id}_roll", :name => "characters[#{character.id}][roll]"}

= link_to 'Show', @encounter
\|
= link_to 'Back', campaign_encounters_path(@campaign)

app/views/encounters/index.html.haml
%h1 Listing encounters

%table
  %tr
    %th Name
    %th
    %th
    %th
    %th

  - @encounters.each do |encounter|
    %tr
      %td= encounter.name
      %td= link_to 'Run', init_campaign_encounter_path(@campaign, encounter)
      %td= link_to 'Show', campaign_encounter_path(@campaign, encounter)
      %td= link_to 'Edit', edit_campaign_encounter_path(@campaign, encounter)
      %td= link_to 'Destroy', campaign_encounter_path(@campaign, encounter), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New encounter', new_campaign_encounter_path(@campaign)
= link_to 'Back to campaigns', campaigns_path

app/views/encounters/init.html.haml
%h1= "Preparing to run #{@encounter.name}"

= link_to "Back", :back

%p
  %h2 Charcters in campaign
  = render :partial => "characters/list", :locals => {:characters => @campaign_characters}
%p
  %h2 Charcters in encounter
  = form_for [@campaign, @encounter], :url => init_campaign_encounter_path(@campaign, @encounter), :html => {:method => 'post', :class => "characters_list"} do |f|
    %table#initialization
      %tr
        %th Name
        %th Base Initiative
        %th Initiative Roll

      - @characters.each do |character|
        %tr.character
          %td.name= character.name
          %td.base_initiative= character.base_initiative
          %td
            %input{:id => "characters_#{character.id}_roll", :name => "characters[#{character.id}][roll]"}

    = f.submit "Run"

app/views/encounters/new.html.haml
%h1= "New encounter for the \"#{@campaign.name}\" campaign"

= render 'form'

= link_to 'Back', campaign_encounters_path(@campaign)

app/views/encounters/run.html.haml
#run
  %h1= "Running #{@encounter.name}: #{@encounter.round}"
  %p
  = form_for [@campaign, @encounter], :url => run_campaign_encounter_path(@campaign, @encounter), :html => {:method => 'post', :id => "running_encounter", :class => "characters_list"} do |f|
    %table#run
      %tr
        %th Name
        %th Initiative

      - @characters.each do |character|
        %tr.character
          %td.name= character.name
          %td
            = text_field_tag "characters[#{character.id}][current_initiative]", character.current_initiative

  %button#previous previous round
  %button#next next round

app/views/encounters/show.html.haml
%p
  %b Name:
  = @encounter.name

  %table#characters
    - @characters.each do |character|
      %tr.character
        %td.initiative= character.base_initiative
        %td.name= character.name


= link_to 'Edit', edit_campaign_encounter_path(@campaign, @encounter)
\|
= link_to 'Back', campaign_encounters_path(@campaign)