config/routes.rb
Gmh::Application.routes.draw do |map|
  resources :campaigns do
    resources :characters
    resources :encounters do
      member do
        get :init, :run
        post :init, :increment_round, :decrement_round
      end
    end
  end

  resources :encounters do
    member do
      get :init
      post :run
    end
  end

  root :to => "campaigns#index"

end

app/models/character.rb
class Character
  include Mongoid::Document

  field :name, :type => String
  field :base_initiative, :type => Integer
  field :current_initiative, :type => Integer
  field :encounter, :type => BSON::ObjectID

  field :initiative, :type => Integer

  #embeds :character_sheet
  embedded_in :campaign, :inverse_of => :characters
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :find_campaign
  before_filter :find_character, :only => [:show, :edit, :update, :destroy]

  def find_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def find_character
    @character = @campaign.characters.find(params[:id])
  end

  def index
    @characters = @campaign.characters.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @character = @campaign.characters.build

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
  end

  def create
    @character = @campaign.characters.build(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to([@campaign, @character], :notice => 'Character was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to([@campaign, @character], :notice => 'Character was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to(campaign_characters_path(@campaign)) }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.haml
= form_for [@campaign, @character] do |f|
  -if @character.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      %ul
        - @character.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :base_initiative
    = f.text_field :base_initiative
  .actions
    = f.submit 'Save'

app/views/characters/_list.html.haml
%table.characters_list
  %tr
    %th Name
    %th Base Initiative

  - characters.each do |character|
    %tr{:id => character.id, :class => 'character'}
      %td= character.name
      %td= character.base_initiative

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

= link_to 'Show', campaign_character_path(@campaign, @character)
\|
= link_to 'Back', campaign_characters_path(@campaign)

app/views/characters/index.html.haml
%h1 Listing characters

%table
  %tr
    %th Name
    %th Base Initiative
    %th
    %th
    %th

  - @characters.each do |character|
    %tr
      %td= character.name
      %td= character.base_initiative
      %td= link_to 'Show', campaign_character_path(@campaign, character)
      %td= link_to 'Edit', edit_campaign_character_path(@campaign, character)
      %td= link_to 'Destroy', campaign_character_path(@campaign, character), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New character', new_campaign_character_path
= link_to 'Back to campaigns', campaigns_path

app/views/characters/new.html.haml
%h1= "New character for the \"#{@campaign.name}\" campaign"

= render 'form'

= link_to 'Back', campaign_characters_path(@campaign)

app/views/characters/show.html.haml
%p
  %b Name:
  = @character.name
%p
  %b Base Initiative:
  = @character.base_initiative

= link_to 'Edit', edit_campaign_character_path(@campaign, @character)
\|
= link_to 'Back', campaign_characters_path(@campaign)