config/routes.rb
Gmh::Application.routes.draw do |map|
  resources :campaigns do
    resources :characters
    resources :encounters do
      member do
        get :init, :run
        post :init, :increment_round, :decrement_round
      end
    end
  end

  resources :encounters do
    member do
      get :init
      post :run
    end
  end

  root :to => "campaigns#index"

end

app/models/campaign.rb
class Campaign
  include Mongoid::Document

  field :name, :type => String

  embeds_many :characters
  has_many_related :encounters
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.xml
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.xml
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.xml
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.xml
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to(@campaign, :notice => 'Campaign was successfully created.') }
        format.xml  { render :xml => @campaign, :status => :created, :location => @campaign }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @campaign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.xml
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to(@campaign, :notice => 'Campaign was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @campaign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.xml
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to(campaigns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.haml
- form_for(@campaign) do |f|
  = f.error_messages
  
  .field
    = f.label :name
    %br
    = f.text_field :name

  .actions
    = f.submit

app/views/campaigns/edit.html.haml
%h1= "Editing the \"#{@campaign.name}\" campaign"

= render 'form'

= link_to "Add an encounter", new_campaign_encounter_path(@campaign)
|
= link_to "Add a character", new_campaign_character_path(@campaign)
|
= link_to 'Show', @campaign
|
= link_to 'Back', campaigns_path

app/views/campaigns/index.html.haml
%h1 Listing campaigns

%table
  %thead
    %tr
      %th Name
      %th{ :colspan => 3 }
  
  %tbody
    - for campaign in @campaigns
      %tr{ :class => cycle(:odd, :even) }
        %td= campaign.name
        %td= link_to 'Show', campaign
        %td= link_to 'Edit', edit_campaign_path(campaign)
        %td= link_to 'Destroy', campaign, :confirm => 'Are you sure?', :method => :delete

%br
= link_to 'New campaign', new_campaign_path

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/show.html.haml
%p
  %strong Name:
  = @campaign.name

%p
  %strong= link_to "Encounters", campaign_encounters_path(@campaign)
  - for encounter in @campaign.encounters.all
    %ul
      %li
        = link_to encounter.name, campaign_encounter_path(@campaign, encounter)
%p
  %strong= link_to "Characters", campaign_characters_path(@campaign)
  - for character in @campaign.characters.all
    %ul
      %li
        = link_to character.name, campaign_character_path(@campaign, character)

= link_to 'Edit', edit_campaign_path(@campaign)
|
= link_to 'Back', campaigns_path